// PatchBoards catalog.js
// Curated software catalog. Mac (Homebrew) and Windows (winget).
// brew: cask name for homebrew-cask, brewFormula: name for homebrew formula
// winget: winget package ID
// github: "owner/repo" for apps that publish official GitHub Releases

const CATALOG = [
  // ── Browsers ────────────────────────────────────────────────────────────────
  { id: 'google-chrome',   name: 'Google Chrome',         category: 'Browser',       desc: 'Fast, secure browser by Google',                    platforms: ['mac','win'], brew: 'google-chrome',        winget: 'Google.Chrome',                                                   homepage: 'https://chromereleases.googleblog.com' },
  { id: 'firefox',         name: 'Mozilla Firefox',       category: 'Browser',        desc: 'Fast browser with strong privacy features',         platforms: ['mac','win'], brew: 'firefox',              winget: 'Mozilla.Firefox',                                                homepage: 'https://www.mozilla.org/firefox/',
    channels: [
      { id: 'release', label: 'Standard Release' },
      { id: 'esr',     label: 'ESR (Extended Support Release)', brew: 'firefox-esr', winget: 'Mozilla.Firefox.ESR' },
    ],
  },
  { id: 'microsoft-edge',  name: 'Microsoft Edge',        category: 'Browser',desc: 'Chromium-based browser by Microsoft',               platforms: ['mac','win'], brew: 'microsoft-edge',       winget: 'Microsoft.Edge',                                                  homepage: 'https://www.microsoft.com/edge' },
  { id: 'brave-browser',   name: 'Brave',                 category: 'Browser',desc: 'Privacy-focused browser with built-in ad blocking', platforms: ['mac','win'], brew: 'brave-browser',        winget: 'Brave.Brave',                          github: 'brave/brave-browser', homepage: 'https://brave.com/' },
  { id: 'arc',             name: 'Arc',                   category: 'Browser',desc: 'Modern browser with workspace organization',        platforms: ['mac'],       brew: 'arc',                  winget: null,                                                              homepage: 'https://arc.net/' },
  { id: 'opera',           name: 'Opera',                 category: 'Browser',desc: 'Browser with built-in VPN and ad blocker',         platforms: ['mac','win'], brew: 'opera',                winget: 'Opera.Opera',                                                     homepage: 'https://www.opera.com/' },
  { id: 'vivaldi',         name: 'Vivaldi',               category: 'Browser',desc: 'Highly customizable browser for power users',      platforms: ['mac','win'], brew: 'vivaldi',              winget: 'VivaldiTechnologies.Vivaldi',                                      homepage: 'https://vivaldi.com/' },
  { id: 'tor-browser',     name: 'Tor Browser',           category: 'Browser',desc: 'Anonymous browsing via the Tor network',           platforms: ['mac','win'], brew: 'tor-browser',          winget: 'TorProject.TorBrowser',                                           homepage: 'https://www.torproject.org/' },

  // ── Developer Tools ──────────────────────────────────────────────────────────
  { id: 'visual-studio-code', name: 'VS Code',            category: 'Developer',desc: 'Popular source code editor by Microsoft',          platforms: ['mac','win'], brew: 'visual-studio-code',   winget: 'Microsoft.VisualStudioCode',           github: 'microsoft/vscode',    homepage: 'https://code.visualstudio.com/' },
  { id: 'cursor',          name: 'Cursor',                category: 'Developer',desc: 'AI-powered code editor built on VS Code',          platforms: ['mac','win'], brew: 'cursor',               winget: 'Anysphere.Cursor',                                                homepage: 'https://www.cursor.com/' },
  { id: 'zed',             name: 'Zed',                   category: 'Developer',desc: 'High-performance multiplayer code editor',          platforms: ['mac'],       brew: 'zed',                  winget: null,                                                              homepage: 'https://zed.dev/' },
  { id: 'sublime-text',    name: 'Sublime Text',          category: 'Developer',desc: 'Sophisticated text editor for code and prose',      platforms: ['mac','win'], brew: 'sublime-text',         winget: 'SublimeHQ.SublimeText.4',                                         homepage: 'https://www.sublimetext.com/' },
  { id: 'github-desktop',  name: 'GitHub Desktop',        category: 'Developer',desc: 'Simplified Git workflow by GitHub',                 platforms: ['mac','win'], brew: 'github',               winget: 'GitHub.GitHubDesktop',                github: 'desktop/desktop',     homepage: 'https://desktop.github.com/' },
  { id: 'sourcetree',      name: 'Sourcetree',            category: 'Developer',desc: 'Free Git client by Atlassian',                      platforms: ['mac','win'], brew: 'sourcetree',           winget: 'Atlassian.Sourcetree',                                            homepage: 'https://www.sourcetreeapp.com/' },
  { id: 'iterm2',          name: 'iTerm2',                category: 'Developer',desc: 'Feature-rich terminal emulator for macOS',          platforms: ['mac'],       brew: 'iterm2',               winget: null,                                                              homepage: 'https://iterm2.com/' },
  { id: 'warp',            name: 'Warp',                  category: 'Developer',desc: 'Modern terminal with AI features',                  platforms: ['mac'],       brew: 'warp',                 winget: null,                                                              homepage: 'https://www.warp.dev/' },
  { id: 'windows-terminal',name: 'Windows Terminal',      category: 'Developer',desc: 'Modern terminal for Windows by Microsoft',          platforms: ['win'],       brew: null,                   winget: 'Microsoft.WindowsTerminal',            github: 'microsoft/terminal',  homepage: 'https://aka.ms/terminal' },
  { id: 'docker',          name: 'Docker Desktop',        category: 'Developer',desc: 'Container platform for developers',                 platforms: ['mac','win'], brew: 'docker',               winget: 'Docker.DockerDesktop',                                            homepage: 'https://www.docker.com/' },
  { id: 'postman',         name: 'Postman',               category: 'Developer',desc: 'API testing and development platform',              platforms: ['mac','win'], brew: 'postman',              winget: 'Postman.Postman',                                                 homepage: 'https://www.postman.com/' },
  { id: 'insomnia',        name: 'Insomnia',              category: 'Developer',desc: 'REST and GraphQL API client',                       platforms: ['mac','win'], brew: 'insomnia',             winget: 'Insomnia.Insomnia',                    github: 'Kong/insomnia',       homepage: 'https://insomnia.rest/' },
  { id: 'tableplus',       name: 'TablePlus',             category: 'Developer',desc: 'Modern database management GUI',                    platforms: ['mac','win'], brew: 'tableplus',            winget: 'TablePlus.TablePlus',                                             homepage: 'https://tableplus.com/' },
  { id: 'dbeaver-community',name: 'DBeaver',              category: 'Developer',desc: 'Universal database tool for developers',            platforms: ['mac','win'], brew: 'dbeaver-community',    winget: 'dbeaver.dbeaver',                      github: 'dbeaver/dbeaver',     homepage: 'https://dbeaver.io/' },
  { id: 'jetbrains-toolbox',name: 'JetBrains Toolbox',   category: 'Developer',desc: 'Manager for JetBrains IDEs and projects',           platforms: ['mac','win'], brew: 'jetbrains-toolbox',    winget: 'JetBrains.Toolbox',                                               homepage: 'https://www.jetbrains.com/toolbox-app/' },
  { id: 'android-studio',  name: 'Android Studio',        category: 'Developer',desc: 'Official IDE for Android development',              platforms: ['mac','win'], brew: 'android-studio',       winget: 'Google.AndroidStudio',                                            homepage: 'https://developer.android.com/studio' },
  { id: 'xcode',           name: 'Xcode',                 category: 'Developer',desc: 'Apple IDE for macOS, iOS, and more',                platforms: ['mac'],       brew: null,                   winget: null,                                                              homepage: 'https://developer.apple.com/xcode/' },
  { id: 'proxyman',        name: 'Proxyman',              category: 'Developer',desc: 'HTTP debugging proxy for macOS',                    platforms: ['mac'],       brew: 'proxyman',             winget: null,                                                              homepage: 'https://proxyman.io/' },
  { id: 'wireshark',       name: 'Wireshark',             category: 'Developer',desc: 'Network protocol analyzer',                         platforms: ['mac','win'], brew: 'wireshark',            winget: 'WiresharkFoundation.Wireshark',        github: 'wireshark/wireshark', homepage: 'https://www.wireshark.org/' },
  { id: 'filezilla',       name: 'FileZilla',             category: 'Developer',desc: 'FTP client and server',                             platforms: ['mac','win'], brew: 'filezilla',            winget: 'TimKosse.FileZillaClient',                                        homepage: 'https://filezilla-project.org/' },
  { id: 'git',             name: 'Git',                   category: 'Developer',desc: 'Distributed version control system', brewType: 'formula', platforms: ['mac','win'], brew: 'git',          winget: 'Git.Git',                              github: 'git-for-windows/git', homepage: 'https://git-scm.com/' },
  { id: 'visual-studio',  name: 'Visual Studio 2022',    category: 'Developer',desc: 'Full-featured IDE for .NET and C++ by Microsoft',   platforms: ['win'],       brew: null,               winget: 'Microsoft.VisualStudio.2022.Community',                           homepage: 'https://visualstudio.microsoft.com/' },
  { id: 'azure-data-studio', name: 'Azure Data Studio',  category: 'Developer',desc: 'Data management tool for SQL Server and Azure SQL', platforms: ['mac','win'], brew: 'azure-data-studio',winget: 'Microsoft.AzureDataStudio',                                       homepage: 'https://azure.microsoft.com/products/data-studio/' },
  { id: 'pgadmin4',       name: 'pgAdmin 4',             category: 'Developer',desc: 'Administration and management platform for PostgreSQL',platforms: ['mac','win'],brew: 'pgadmin4',         winget: 'PostgreSQL.pgAdmin',                                              homepage: 'https://www.pgadmin.org/' },
  { id: 'github-cli',     name: 'GitHub CLI',            category: 'Developer',desc: 'Official GitHub command-line tool', brewType: 'formula', platforms: ['mac','win'], brew: 'gh',           winget: 'GitHub.cli',                           github: 'cli/cli',             homepage: 'https://cli.github.com/' },
  { id: 'terraform',      name: 'Terraform',             category: 'Developer',desc: 'Infrastructure as code tool by HashiCorp', brewType: 'formula', platforms: ['mac','win'], brew: 'terraform', winget: 'Hashicorp.Terraform',                github: 'hashicorp/terraform',  homepage: 'https://www.terraform.io/' },
  { id: 'kubectl',        name: 'kubectl',               category: 'Developer',desc: 'Command-line tool for controlling Kubernetes clusters', brewType: 'formula', platforms: ['mac','win'], brew: 'kubernetes-cli', winget: 'Kubernetes.kubectl',                                    homepage: 'https://kubernetes.io/docs/reference/kubectl/' },
  { id: 'lens',           name: 'Lens',                  category: 'Developer',desc: 'Kubernetes IDE for cluster management',               platforms: ['mac','win'], brew: 'lens',             winget: 'Mirantis.Lens',                                                   homepage: 'https://k8slens.dev/' },
  { id: 'rancher-desktop',name: 'Rancher Desktop',       category: 'Developer',desc: 'Container management and Kubernetes on the desktop',  platforms: ['mac','win'], brew: 'rancher',          winget: 'suse.RancherDesktop',                  github: 'rancher-sandbox/rancher-desktop', homepage: 'https://rancherdesktop.io/' },
  { id: 'burp-suite',     name: 'Burp Suite Community',  category: 'Developer',desc: 'Web security testing platform by PortSwigger',       platforms: ['mac','win'], brew: 'burp-suite',       winget: 'PortSwigger.BurpSuite.Community',                                  homepage: 'https://portswigger.net/burp/communitydownload' },

  // ── Communication ────────────────────────────────────────────────────────────
  { id: 'slack',           name: 'Slack',                 category: 'Communication',desc: 'Team messaging and collaboration platform',         platforms: ['mac','win'], brew: 'slack',                winget: 'SlackTechnologies.Slack',                                          homepage: 'https://slack.com/' },
  { id: 'discord',         name: 'Discord',               category: 'Communication',desc: 'Voice, video, and text for communities',            platforms: ['mac','win'], brew: 'discord',              winget: 'Discord.Discord',                                                 homepage: 'https://discord.com/' },
  { id: 'microsoft-teams', name: 'Microsoft Teams',       category: 'Communication',desc: 'Workplace collaboration by Microsoft',              platforms: ['mac','win'], brew: 'microsoft-teams',      winget: 'Microsoft.Teams',                                                 homepage: 'https://www.microsoft.com/microsoft-teams/' },
  { id: 'zoom',            name: 'Zoom',                  category: 'Communication',desc: 'Video conferencing and online meetings',            platforms: ['mac','win'], brew: 'zoom',                 winget: 'Zoom.Zoom',                                                       homepage: 'https://zoom.us/' },
  { id: 'telegram',        name: 'Telegram',              category: 'Communication',desc: 'Fast, secure messaging app',                        platforms: ['mac','win'], brew: 'telegram',             winget: 'Telegram.TelegramDesktop',             github: 'telegramdesktop/tdesktop', homepage: 'https://telegram.org/' },
  { id: 'signal',          name: 'Signal',                category: 'Communication',desc: 'Private, end-to-end encrypted messaging',           platforms: ['mac','win'], brew: 'signal',               winget: 'OpenWhisperSystems.Signal',             github: 'signalapp/Signal-Desktop', homepage: 'https://signal.org/' },
  { id: 'whatsapp',        name: 'WhatsApp',              category: 'Communication',desc: 'Messaging app by Meta',                             platforms: ['mac','win'], brew: 'whatsapp',             winget: 'WhatsApp.WhatsApp',                                               homepage: 'https://www.whatsapp.com/' },
  { id: 'skype',           name: 'Skype',                 category: 'Communication',desc: 'Video and voice calls by Microsoft',                platforms: ['mac','win'], brew: 'skype',                winget: 'Microsoft.Skype',                                                 homepage: 'https://www.skype.com/' },
  { id: 'webex',           name: 'Webex',                 category: 'Communication',desc: 'Video conferencing by Cisco',                       platforms: ['mac','win'], brew: 'webex',                winget: 'Cisco.WebexTeams',                                                homepage: 'https://www.webex.com/' },
  { id: 'ringcentral',    name: 'RingCentral',           category: 'Communication',desc: 'Unified communications platform for business',      platforms: ['mac','win'], brew: 'ringcentral',          winget: 'RingCentral.RingCentral',                                         homepage: 'https://www.ringcentral.com/' },
  { id: 'miro',           name: 'Miro',                  category: 'Communication',desc: 'Online collaborative whiteboard for teams',          platforms: ['mac','win'], brew: 'miro',                 winget: 'Miro.Miro',                                                       homepage: 'https://miro.com/' },

  // ── Productivity ─────────────────────────────────────────────────────────────
  { id: 'notion',          name: 'Notion',                category: 'Productivity',desc: 'All-in-one workspace for notes and projects',       platforms: ['mac','win'], brew: 'notion',               winget: 'Notion.Notion',                                                   homepage: 'https://www.notion.so/' },
  { id: 'notpad++',        name: 'Notepad++',             category: 'Productivity',desc: 'Text editor and source code editor for Windows',    platforms: ['mac','win'], brew: 'notpad++',             winget: 'Notepad++.Notepad++',                                             homepage: 'https://notepad-plus-plus.org' },
  { id: 'obsidian',        name: 'Obsidian',              category: 'Productivity',desc: 'Markdown knowledge base and note-taking app',       platforms: ['mac','win'], brew: 'obsidian',             winget: 'Obsidian.Obsidian',                    github: 'obsidianmd/obsidian-releases', homepage: 'https://obsidian.md/' },
  { id: '1password',       name: '1Password',             category: 'Productivity',desc: 'Password manager for individuals and teams',        platforms: ['mac','win'], brew: '1password',            winget: 'AgileBits.1Password',                                             homepage: 'https://1password.com/' },
  { id: 'bitwarden',       name: 'Bitwarden',             category: 'Productivity',desc: 'Open-source password manager',                      platforms: ['mac','win'], brew: 'bitwarden',            winget: 'Bitwarden.Bitwarden',                                             homepage: 'https://bitwarden.com/' },
  { id: 'raycast',         name: 'Raycast',               category: 'Productivity',desc: 'macOS productivity launcher and automation',        platforms: ['mac'],       brew: 'raycast',              winget: null,                                                              homepage: 'https://www.raycast.com/' },
  { id: 'alfred',          name: 'Alfred',                category: 'Productivity',desc: 'macOS launcher with workflows and clipboard',       platforms: ['mac'],       brew: 'alfred',               winget: null,                                                              homepage: 'https://www.alfredapp.com/' },
  { id: 'todoist',         name: 'Todoist',               category: 'Productivity',desc: 'Task manager and to-do list',                       platforms: ['mac','win'], brew: 'todoist',              winget: 'Doist.Todoist',                                                   homepage: 'https://todoist.com/' },
  { id: 'loom',            name: 'Loom',                  category: 'Productivity',desc: 'Screen recorder and video messaging',               platforms: ['mac','win'], brew: 'loom',                 winget: 'Loom.Loom',                                                       homepage: 'https://www.loom.com/' },
  { id: 'dropbox',         name: 'Dropbox',               category: 'Productivity',desc: 'Cloud storage and file sync',                       platforms: ['mac','win'], brew: 'dropbox',              winget: 'Dropbox.Dropbox',                                                 homepage: 'https://www.dropbox.com/' },
  { id: 'google-drive',    name: 'Google Drive',          category: 'Productivity',desc: 'Cloud storage and backup by Google',                platforms: ['mac','win'], brew: 'google-drive',         winget: 'Google.GoogleDrive',                                              homepage: 'https://drive.google.com/' },
  { id: 'evernote',        name: 'Evernote',              category: 'Productivity',desc: 'Note-taking and organization app',                  platforms: ['mac','win'], brew: 'evernote',             winget: 'Evernote.Evernote',                                               homepage: 'https://evernote.com/' },
  { id: 'libreoffice',     name: 'LibreOffice',           category: 'Productivity',desc: 'Free, open-source office suite',                    platforms: ['mac','win'], brew: 'libreoffice',          winget: 'TheDocumentFoundation.LibreOffice',                                homepage: 'https://www.libreoffice.org/' },
  { id: 'microsoft-office',name: 'Microsoft Office',      category: 'Productivity',desc: 'Microsoft Office Suite (Word, Excel, PowerPoint)',  platforms: ['mac','win'], brew: 'microsoft-office',     winget: 'Microsoft.Office',                                                homepage: 'https://www.microsoft.com/microsoft-365/' },
  { id: 'typora',          name: 'Typora',                category: 'Productivity',desc: 'Minimal, distraction-free Markdown editor',         platforms: ['mac','win'], brew: 'typora',               winget: 'typora.typora',                                                   homepage: 'https://typora.io/' },
  { id: 'bear',            name: 'Bear',                  category: 'Productivity',desc: 'Beautiful note-taking app for Mac and iOS',         platforms: ['mac'],       brew: 'bear',                 winget: null,                                                              homepage: 'https://bear.app/' },
  { id: 'microsoft-onedrive', name: 'Microsoft OneDrive', category: 'Productivity',desc: 'Cloud storage and file sync by Microsoft',          platforms: ['mac','win'], brew: 'microsoft-onedrive',   winget: 'Microsoft.OneDrive',                                              homepage: 'https://www.microsoft.com/microsoft-365/onedrive/' },
  { id: 'box-drive',      name: 'Box Drive',             category: 'Productivity',desc: 'Enterprise cloud content management and file sync',  platforms: ['mac','win'], brew: 'box-drive',            winget: 'Box.Box',                                                         homepage: 'https://www.box.com/' },
  { id: 'grammarly-desktop', name: 'Grammarly',          category: 'Productivity',desc: 'AI writing assistant for grammar and style',         platforms: ['mac','win'], brew: 'grammarly-desktop',    winget: 'Grammarly.Grammarly',                                             homepage: 'https://www.grammarly.com/' },
  { id: 'adobe-acrobat-reader', name: 'Adobe Acrobat Reader', category: 'Productivity',desc: 'View, sign, and annotate PDFs by Adobe',        platforms: ['mac','win'], brew: 'adobe-acrobat-reader', winget: 'Adobe.Acrobat.Reader.64-bit',                                     homepage: 'https://www.adobe.com/acrobat/pdf-reader.html' },
  { id: 'asana',          name: 'Asana',                 category: 'Productivity',desc: 'Project management and team collaboration platform', platforms: ['mac','win'], brew: 'asana',                winget: 'Asana.Asana',                                                     homepage: 'https://asana.com/' },
  { id: 'microsoft-to-do',name: 'Microsoft To Do',       category: 'Productivity',desc: 'Task management app by Microsoft',                  platforms: ['mac','win'], brew: 'microsoft-to-do',      winget: 'Microsoft.Todo',                                                  homepage: 'https://todo.microsoft.com/' },

  // ── Media ────────────────────────────────────────────────────────────────────
  { id: 'spotify',         name: 'Spotify',               category: 'Media',desc: 'Music and podcast streaming service',               platforms: ['mac','win'], brew: 'spotify',              winget: 'Spotify.Spotify',                                                 homepage: 'https://www.spotify.com/' },
  { id: 'vlc',             name: 'VLC',                   category: 'Media',desc: 'Open-source, cross-platform media player',          platforms: ['mac','win'], brew: 'vlc',                  winget: 'VideoLAN.VLC',                                                    homepage: 'https://www.videolan.org/vlc/' },
  { id: 'iina',            name: 'IINA',                  category: 'Media',desc: 'Modern, native media player for macOS',             platforms: ['mac'],       brew: 'iina',                 winget: null,                                                              homepage: 'https://iina.io/' },
  { id: 'handbrake',       name: 'HandBrake',             category: 'Media',desc: 'Open-source video transcoder',                      platforms: ['mac','win'], brew: 'handbrake',            winget: 'HandBrake.HandBrake',                  github: 'HandBrake/HandBrake', homepage: 'https://handbrake.fr/' },
  { id: 'obs',             name: 'OBS Studio',            category: 'Media',desc: 'Free streaming and screen recording software',      platforms: ['mac','win'], brew: 'obs',                  winget: 'OBSProject.OBSStudio',                 github: 'obsproject/obs-studio', homepage: 'https://obsproject.com/' },
  { id: 'plex',            name: 'Plex',                  category: 'Media',desc: 'Personal media server and player',                  platforms: ['mac','win'], brew: 'plex',                 winget: 'Plex.Plexamp',                                                    homepage: 'https://www.plex.tv/' },
  { id: 'audacity',        name: 'Audacity',              category: 'Media',desc: 'Free, open-source audio editor',                    platforms: ['mac','win'], brew: 'audacity',             winget: 'Audacity.Audacity',                    github: 'audacity/audacity',   homepage: 'https://www.audacityteam.org/' },
  { id: 'kodi',            name: 'Kodi',                  category: 'Media',desc: 'Open-source home theater software',                 platforms: ['mac','win'], brew: 'kodi',                 winget: 'XBMCFoundation.Kodi',                  github: 'xbmc/xbmc',           homepage: 'https://kodi.tv/' },

  // ── Design ───────────────────────────────────────────────────────────────────
  { id: 'figma',           name: 'Figma',                 category: 'Design',desc: 'Collaborative design and prototyping tool',         platforms: ['mac','win'], brew: 'figma',                winget: 'Figma.Figma',                                                     homepage: 'https://www.figma.com/' },
  { id: 'sketch',          name: 'Sketch',                category: 'Design',desc: 'Vector graphics editor for macOS UI design',        platforms: ['mac'],       brew: 'sketch',               winget: null,                                                              homepage: 'https://www.sketch.com/' },
  { id: 'adobe-creative-cloud', name: 'Adobe Creative Cloud', category: 'Design',desc: 'Hub for all Adobe creative apps',                   platforms: ['mac','win'], brew: 'adobe-creative-cloud', winget: 'Adobe.CreativeCloud',                                             homepage: 'https://www.adobe.com/creativecloud.html' },
  { id: 'inkscape',        name: 'Inkscape',              category: 'Design',desc: 'Free, open-source vector graphics editor',          platforms: ['mac','win'], brew: 'inkscape',             winget: 'Inkscape.Inkscape',                    github: 'inkscape/inkscape',   homepage: 'https://inkscape.org/' },
  { id: 'gimp',            name: 'GIMP',                  category: 'Design',desc: 'Free, open-source image editor',                    platforms: ['mac','win'], brew: 'gimp',                 winget: 'GIMP.GIMP',                                                       homepage: 'https://www.gimp.org/' },
  { id: 'blender',         name: 'Blender',               category: 'Design',desc: 'Open-source 3D creation suite',                     platforms: ['mac','win'], brew: 'blender',              winget: 'BlenderFoundation.Blender',                                        homepage: 'https://www.blender.org/' },

  // ── Security ─────────────────────────────────────────────────────────────────
  { id: 'malwarebytes',    name: 'Malwarebytes',          category: 'Security',desc: 'Anti-malware and cybersecurity software',           platforms: ['mac','win'], brew: 'malwarebytes',         winget: 'Malwarebytes.Malwarebytes',                                        homepage: 'https://www.malwarebytes.com/' },
  { id: 'keepassxc',       name: 'KeePassXC',             category: 'Security',desc: 'Open-source cross-platform password manager',       platforms: ['mac','win'], brew: 'keepassxc',            winget: 'KeePassXCTeam.KeePassXC',              github: 'keepassxc/keepassxc', homepage: 'https://keepassxc.org/' },
  { id: 'little-snitch',   name: 'Little Snitch',         category: 'Security',desc: 'Network monitor and outbound firewall for macOS',   platforms: ['mac'],       brew: 'little-snitch',        winget: null,                                                              homepage: 'https://www.obdev.at/products/littlesnitch/' },
  { id: 'nordvpn',         name: 'NordVPN',               category: 'Security',desc: 'VPN service for privacy and security',              platforms: ['mac','win'], brew: 'nordvpn',              winget: 'NordVPN.NordVPN',                                                 homepage: 'https://nordvpn.com/' },
  { id: 'expressvpn',      name: 'ExpressVPN',            category: 'Security',desc: 'Fast and secure VPN service',                       platforms: ['mac','win'], brew: 'expressvpn',           winget: 'ExpressVPN.ExpressVPN',                                            homepage: 'https://www.expressvpn.com/' },
  { id: 'veracrypt',       name: 'VeraCrypt',             category: 'Security',desc: 'Open-source disk encryption software',              platforms: ['mac','win'], brew: 'veracrypt',            winget: 'IDRIX.VeraCrypt',                      github: 'veracrypt/VeraCrypt', homepage: 'https://www.veracrypt.fr/' },
  { id: 'cisco-secure-client', name: 'Cisco Secure Client', category: 'Security',desc: 'Enterprise VPN client by Cisco (formerly AnyConnect)', platforms: ['mac','win'], brew: 'cisco-secure-client', winget: 'Cisco.CiscoSecureClient',                                         homepage: 'https://www.cisco.com/c/en/us/products/security/anyconnect-secure-mobility-client/' },
  { id: 'forticlient',    name: 'FortiClient VPN',       category: 'Security',desc: 'Enterprise VPN and endpoint security by Fortinet',   platforms: ['mac','win'], brew: 'forticlient',          winget: 'Fortinet.FortiClientVPN',                                         homepage: 'https://www.fortinet.com/products/endpoint-security/forticlient' },
  { id: 'okta-verify',    name: 'Okta Verify',           category: 'Security',desc: 'Multi-factor authentication app by Okta',            platforms: ['mac','win'], brew: 'okta-verify',          winget: 'Okta.OktaVerify',                                                 homepage: 'https://www.okta.com/' },
  { id: 'beyond-compare', name: 'Beyond Compare',        category: 'Security',desc: 'File and folder comparison and sync tool',           platforms: ['mac','win'], brew: 'beyond-compare',       winget: 'ScooterSoftware.BeyondCompare5',                                  homepage: 'https://www.scootersoftware.com/' },
  { id: 'splunk',         name: 'Splunk',                category: 'Security',desc: 'Platform for searching, monitoring, and analyzing machine data (SIEM)', platforms: ['mac','win'], brew: 'splunk',              winget: 'Splunk.Splunk',                                                   homepage: 'https://www.splunk.com/' },

  // ── Remote Access ────────────────────────────────────────────────────────────
  { id: 'teamviewer',     name: 'TeamViewer',            category: 'Remote Access',desc: 'Remote desktop access and IT support platform',    platforms: ['mac','win'], brew: 'teamviewer',           winget: 'TeamViewer.TeamViewer',                                           homepage: 'https://www.teamviewer.com/' },
  { id: 'anydesk',        name: 'AnyDesk',               category: 'Remote Access',desc: 'Fast remote desktop software for enterprise support', platforms: ['mac','win'], brew: 'anydesk',           winget: 'AnyDeskSoftwareGmbH.AnyDesk',                                     homepage: 'https://anydesk.com/' },
  { id: 'microsoft-remote-desktop', name: 'Microsoft Remote Desktop', category: 'Remote Access',desc: 'Connect to Windows PCs and virtual desktops', platforms: ['mac'], brew: 'microsoft-remote-desktop', winget: null,                                                       homepage: 'https://aka.ms/rdmac' },
  { id: 'citrix-workspace', name: 'Citrix Workspace',   category: 'Remote Access',desc: 'Access virtual apps and desktops via Citrix',      platforms: ['mac','win'], brew: 'citrix-workspace',     winget: 'Citrix.Workspace',                                                homepage: 'https://www.citrix.com/products/citrix-workspace/' },
  { id: 'vmware-horizon-client', name: 'VMware Horizon Client', category: 'Remote Access',desc: 'Access VMware virtual desktops and apps',  platforms: ['mac','win'], brew: 'vmware-horizon-client', winget: 'VMware.HorizonClient',                                           homepage: 'https://www.vmware.com/products/horizon.html' },

  // ── Utilities ────────────────────────────────────────────────────────────────
  { id: 'the-unarchiver',  name: 'The Unarchiver',        category: 'Utilities',desc: 'Archive extractor supporting many formats on macOS', platforms: ['mac'],       brew: 'the-unarchiver',       winget: null,                                                              homepage: 'https://theunarchiver.com/' },
  { id: '7zip',            name: '7-Zip',                 category: 'Utilities',desc: 'File archiver with high compression ratio',          platforms: ['win'],       brew: null,                   winget: '7zip.7zip',                            github: 'ip7z/7zip',           homepage: 'https://www.7-zip.org/' },
  { id: 'rectangle',       name: 'Rectangle',             category: 'Utilities',desc: 'Window management for macOS with keyboard shortcuts',platforms: ['mac'],       brew: 'rectangle',            winget: null,                                                              homepage: 'https://rectangleapp.com/' },
  { id: 'appcleaner',      name: 'AppCleaner',            category: 'Utilities',desc: 'Thoroughly uninstall unwanted apps on macOS',       platforms: ['mac'],       brew: 'appcleaner',           winget: null,                                                              homepage: 'https://freemacsoft.net/appcleaner/' },
  { id: 'balenaetcher',    name: 'balenaEtcher',          category: 'Utilities',desc: 'Flash OS images to SD cards and USB drives',        platforms: ['mac','win'], brew: 'balenaetcher',         winget: 'Balena.Etcher',                        github: 'balena-io/etcher',    homepage: 'https://etcher.balena.io/' },
  { id: 'stats',           name: 'Stats',                 category: 'Utilities',desc: 'macOS system monitor in the menu bar',              platforms: ['mac'],       brew: 'stats',                winget: null,                                                              homepage: 'https://github.com/exelban/stats' },
  { id: 'cleanmymac',      name: 'CleanMyMac X',          category: 'Utilities',desc: 'Mac optimization and cleaning tool by MacPaw',      platforms: ['mac'],       brew: 'cleanmymac',           winget: null,                                                              homepage: 'https://cleanmymac.com/' },
  { id: 'powertoys',       name: 'PowerToys',             category: 'Utilities',desc: 'Windows system utilities by Microsoft',             platforms: ['win'],       brew: null,                   winget: 'Microsoft.PowerToys',                  github: 'microsoft/PowerToys', homepage: 'https://learn.microsoft.com/windows/powertoys/' },
  { id: 'autohotkey',      name: 'AutoHotkey',            category: 'Utilities',desc: 'Windows automation scripting language',             platforms: ['win'],       brew: null,                   winget: 'AutoHotkey.AutoHotkey',                github: 'AutoHotkey/AutoHotkey', homepage: 'https://www.autohotkey.com/' },
  { id: 'everything',      name: 'Everything',            category: 'Utilities',desc: 'Instant file search by filename for Windows',       platforms: ['win'],       brew: null,                   winget: 'voidtools.Everything',                                            homepage: 'https://www.voidtools.com/' },
  { id: 'utm',             name: 'UTM',                   category: 'Utilities',desc: 'Virtual machine host for macOS',                    platforms: ['mac'],       brew: 'utm',                  winget: null,                                                              homepage: 'https://mac.getutm.app/' },
  { id: 'virtualbox',      name: 'VirtualBox',            category: 'Utilities',desc: 'Open-source virtualization platform',               platforms: ['mac','win'], brew: 'virtualbox',           winget: 'Oracle.VirtualBox',                                               homepage: 'https://www.virtualbox.org/' },
  { id: 'bartender',       name: 'Bartender',             category: 'Utilities',desc: 'Menu bar item organizer for macOS',                 platforms: ['mac'],       brew: 'bartender',            winget: null,                                                              homepage: 'https://www.macbartender.com/' },

];

const CATALOG_CATEGORIES = [...new Set(CATALOG.map(a => a.category))].sort();

function getCatalogApp(id) {
  return CATALOG.find(a => a.id === id) || Store.getCustomApps().find(a => a.id === id) || null;
}

function filterCatalog({ query = '', platform = 'all', category = 'all' } = {}) {
  const allApps = [...CATALOG, ...Store.getCustomApps()];
  const q = query.toLowerCase().trim();
  return allApps.filter(app => {
    if (platform !== 'all' && !app.platforms.includes(platform)) return false;
    if (category !== 'all' && app.category !== category) return false;
    if (q && !app.name.toLowerCase().includes(q) && !app.desc.toLowerCase().includes(q) && !app.category.toLowerCase().includes(q)) return false;
    return true;
  });
}
